### ISSUE TITLE
ERROR: Could not lookup : Servname not supported for ai_socktype

### ISSUE THREAD

**Issue by Reiji87** [kylefarris/clamscan#19]
I was trying to run a scan using my node app, during the callback I got an error as follow

`ERROR: Communication error`

So I tried to run the scan manually, the error message is 
`ERROR: Could not lookup : Servname not supported for ai_socktype`

The command used for run is:
clamdscan --no-summary --fdpass --config-file=/etc/clamav/clamd.conf /home/ubuntu/testing/up/testing12324

Anyone encountered this before? 
Thank you :)

**Comment by shogan94** [comment]
Did you ever find a solution to this? I just recently started getting this error also. In the meantime I switched to using clamscan instead of clamdscan

**Comment by derMani** [comment]
The user who runs the node instance, must be in the unix group clamscan. 

usermod --groups clamscan --append <user> 

This should do the trick
