### ISSUE TITLE
Could not connect to clamd on LocalSocket

### ISSUE THREAD

**Issue by BradleyDHobbs** [kylefarris/clamscan#25]
"ERROR: Could not connect to clamd on LocalSocket /var/run/clamd.scan/clamd.sock: Permission denied"

Running this from a directory in the home folder.

Any ideas?

**Comment by kylefarris** [comment]
Hey @BradleyDHobbs,

It likely has something to do with the permissions of your clamd config. This problem isn't really in the scope of this module, but I'll see if I can help you out anyways. What OS and OS version are you running on? What does your clamav config look like?

**Comment by BradleyDHobbs** [comment]
Yeah you were right. It was a permissions issue. I have to do some messing around with the virusgroup group. Got it working eventually. 

On a side note, any way to use async await and/or promises with the methods?

**Comment by kylefarris** [comment]
Hey @BradleyDHobbs, I just released version 1.0.0 (big update) last week and it definitely supports Promises and Async/await now. So, please try it out and let me know if you have any issues. You will want to read the release notes for the release as there are some changes to the API (mostly to do with out you init the module).
