### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by vdanyliv** [kylefarris/clamscan#33]
After trying to check directory got this error

```
viruses = Array.from(new Set(viruses));
TypeError: Assignment to constant variable.
```
And after some investigation, I found an issue in **scan_files** method.

**line 1087**
```
let viruses = [];
```
**line 1093**
```
const viruses = stdout.trim().split(String.fromCharCode(10)).map(v => /FOUND\n?$/.test(v) ? v.replace(/(.+):\s+(.+)FOUND\n?$/, "$2").trim() : null).filter(v => !!v);
```

**line 1119**
```
viruses = Array.from(new Set(viruses));
```

A pretty easy solution will be to rename a variable in the line 1093

**Comment by kylefarris** [comment]
This bug is fixed in v1.0.4. Thanks for the bug report.
