### ISSUE TITLE
Could not find file to scan

### ISSUE THREAD

**Issue by ritika-innani** [kylefarris/clamscan#34]
Trying to upload a file with space in the file name, it's throwing this error 'Could not find file to scan!'
After investigation, found that it is replacing the spaces with '\ ' 
After that it is failing at fs_access function.

**Comment by kylefarris** [comment]
Replacing spaces with `\ ` is standard Unix procedure but looking at the code, it looks like we're double-up on the back-slashes which would not be what we want. When you say "after that, it is failing at fs_access function", what do you mean? What is it saying? What's the error message?
