### ISSUE TITLE
TypeError: clamscan.passthrough is not a function

### ISSUE THREAD

**Issue by midnightcodr** [kylefarris/clamscan#46]
I am trying out the passthrough() example but unfortunately I am getting this
```
TypeError: clamscan.passthrough is not a function
```
I am initializing the connection options as

```js
const clamscan = new NodeClam().init({
    clamdscan: {
        host: '127.0.0.1',
        port: 3310,
    }
});

```
as I am running the clamav service in a docker container (`telnet 127.0.0.1 3310` works btw).

Ideas?

**Comment by midnightcodr** [comment]
Never mind. I found the cause of the error - I didn't use `.then()` or `await` on the `clamscan` instance. To fix the problem is as simple as
```javascript
const clamscan = new NodeClam()
await clamscan.init({
    clamdscan: {
        host: '127.0.0.1',
        port: 3310,
    }
});
```

**Comment by kylefarris** [comment]
Great! Glad you figured it out. :-) I'm sorry I never saw this issue come through--I would have been happy to point that out.

**Comment by midnightcodr** [comment]
No problem. I am so happy to find your library that provides the Stream/Transform ability that I need in my application.
