### ISSUE TITLE
get_version() Promise problem

### ISSUE THREAD

**Issue by benzino77** [kylefarris/clamscan#47]
Hi there,

`get_version()` function does not return reject in case of error
https://github.com/kylefarris/clamscan/blob/5f557c970817fe8c578ec3f7ad3bcbcef4cf5538/index.js#L690

I think that it should be ` return (has_cb ? cb(err, null) : reject(err));`

**Comment by kylefarris** [comment]
I believe you're right. Surprised the unit tests didn't catch this.

**Comment by benzino77** [comment]
Thanks for a merge!

**Comment by kylefarris** [comment]
No problem!

I'll get a new patched version out tomorrow. Going to try to get a few other minor bugs/issues put into it.

Kyle
