### ISSUE TITLE
sudo freshclam error

### ISSUE THREAD

**Issue by M0dred** [kylefarris/clamscan#49]
Tue May 19 00:23:11 2020 -> !Failed to load new database: Malformed database
Tue May 19 00:23:12 2020 -> ^Database load exited with "Test failed" (8)
Tue May 19 00:23:12 2020 -> !Database test FAILED.
Tue May 19 00:23:12 2020 -> !Unexpected error when attempting to update database: daily
Tue May 19 00:23:12 2020 -> ^fc_update_databases: fc_update_database failed: Test failed (8)
Tue May 19 00:23:12 2020 -> !Database update process failed: Test failed (8)
Tue May 19 00:23:12 2020 -> !Update failed.

**Comment by kylefarris** [comment]
This may just be because the database server was down? This looks like an issue with `fresclam` not necessarily the clamscan module. Maybe you can give some more context instead of just a log output?
