### ISSUE TITLE
Init does not reject errors.

### ISSUE THREAD

**Issue by GeorgeCalvert** [kylefarris/clamscan#55]
We were trying to catch startup errors in the `init` method but not seeing them.  Thanks to our team member @saijian2008, we found the problem is index.js:571.  It should use `reject` not `resolve`, i.e.:
```
return (has_cb ? cb(err, false) : reject(err));
```

**Comment by kylefarris** [comment]
Interesting... I thought I just resolved this issue with the latest release. I'll go back and check. Thanks!

**Comment by niftylettuce** [comment]
See #57 @kylefarris - can you please fix this? I would gladly tip you over PayPal a bug bounty award.

Currently using your great project in https://forwardemail.net and https://spamscanner.net.

**Comment by kylefarris** [comment]
Do you think this is the problem on #57? If so, I'll take care of it really quick.

**Comment by kylefarris** [comment]
I've patched the module. The patch is available in v1.3.3
