### ISSUE TITLE
Consider returning stdout and stderr in the error object data property

### ISSUE THREAD

**Issue by Shintu-J-Thattakunnil** [kylefarris/clamscan#79]
Right now within the is_infected method if the clam scan fails there is no way to know the exact error from the daemon

**Comment by kylefarris** [comment]
I'll take a look.

**Comment by Shintu-J-Thattakunnil** [comment]
Thank you. Please let me know if you need more info.

**Comment by kylefarris** [comment]
This was fixed some time back. You can now access the original response from the daemon via `resultString`.
